### ISSUE TITLE
Handle no data being returned for api calls

### ISSUE THREAD

**Issue by chrisducey01** [chrisducey01/hey_liri#3]
When I searched bands in town and mispelled the artist name, I got an error about response.data.forEach not being a function.  Need to investigate and see what is returned when no results are found, then handle that in the code.

**Comment by chrisducey01** [comment]
Christophers-MacBook-Pro:hey_liri christopherducey$ node liri.js concert-this Madonaa
(node:36216) UnhandledPromiseRejectionWarning: Error: Request failed with status code 404
    at createError (/Users/christopherducey/Documents/Repos/uofa_bootcamp/hey_liri/node_modules/axios/lib/core/createError.js:16:15)
    at settle (/Users/christopherducey/Documents/Repos/uofa_bootcamp/hey_liri/node_modules/axios/lib/core/settle.js:17:12)
    at IncomingMessage.handleStreamEnd (/Users/christopherducey/Documents/Repos/uofa_bootcamp/hey_liri/node_modules/axios/lib/adapters/http.js:237:11)
    at IncomingMessage.emit (events.js:201:15)
    at endReadableNT (_stream_readable.js:1130:12)
    at processTicksAndRejections (internal/process/task_queues.js:84:17)
(node:36216) UnhandledPromiseRejectionWarning: Unhandled promise rejection. This error originated either by throwing inside of an async function without a catch block, or by rejecting a promise which was not handled with .catch(). (rejection id: 2)
(node:36216) [DEP0018] DeprecationWarning: Unhandled promise rejections are deprecated. In the future, promise rejections that are not handled will terminate the Node.js process with a non-zero exit code.
